Apply the patch for the async signals race condition in Sendmail.

diff --git a/etc/daily b/etc/daily
--- a/etc/daily
+++ b/etc/daily
@@ -1,128 +1,176 @@
 #!/bin/sh -
 #
-#	@(#)daily	5.12 (Berkeley) 5/24/91
+#	$OpenBSD: daily,v 1.52 2005/11/24 12:08:15 pedro Exp $
+#	From: @(#)daily	8.2 (Berkeley) 1/25/94
 #
-PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local
-host=`hostname -s`
-echo "Subject: $host daily run output"
+PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
+bak=/var/backups
+
+sysctl -n kern.version
+uptime
+
+if [ -f /etc/daily.local ]; then
+	echo ""
+	echo "Running daily.local:"
+	. /etc/daily.local
+fi
+
+TMP=`mktemp /tmp/_daily.XXXXXXXXXX` || exit 1
+OUT=`mktemp /tmp/_security.XXXXXXXXXX` || {
+	rm -f ${TMP}
+	exit 1
+}
+
+trap 'rm -f $TMP $OUT' 0 1 15
 
 echo ""
 echo "Removing scratch and junk files:"
-if [ -d /tmp -a ! -h /tmp ]; then
+if [ -d /tmp -a ! -L /tmp ]; then
 	cd /tmp && {
-	find . -type f -atime +3 -exec rm -f -- {} \;
-	find . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
-	    >/dev/null 2>&1; }
+	find -x . \
+	    \( -path './ssh-*' -o -path ./.X11-unix -o -path ./.ICE-unix \) \
+	    -prune -o -type f -atime +3 -execdir rm -f -- {} \;
+	find -x . -type d -mtime +1 ! -path ./vi.recover ! -path ./.X11-unix \
+	    ! -path ./.ICE-unix ! -name . -execdir rmdir -- {} \; >/dev/null 2>&1; }
 fi
 
-if [ -d /var/tmp -a ! -h /var/tmp ]; then
+if [ -d /var/tmp -a ! -L /var/tmp ]; then
 	cd /var/tmp && {
-	find . ! -name . -atime +7 -exec rm -f -- {} \;
-	find . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
-	    >/dev/null 2>&1; }
+	find -x . \
+	    \( -path './ssh-*' -o -path ./.X11-unix -o -path ./.ICE-unix \) \
+	    -prune -o ! -type d -atime +7 -execdir rm -f -- {} \;
+	find -x . -type d -mtime +1 ! -path ./vi.recover ! -path ./.X11-unix \
+	    ! -path ./.ICE-unix ! -name . -execdir rmdir -- {} \; >/dev/null 2>&1; }
 fi
 
-if [ -d /scratch -a ! -h /scratch ]; then
-	cd /scratch && {
-	find . ! -name . -atime +1 -exec rm -f -- {} \;
-	find . ! -name . -type d -mtime +1 -exec rmdir -- {} \; \
-	    >/dev/null 2>&1; }
-fi
+# Additional junk directory cleanup would go like this:
+#if [ -d /scratch -a ! -L /scratch ]; then
+#	cd /scratch && {
+#	find . ! -name . -atime +1 -execdir rm -f -- {} \;
+#	find . ! -name . -type d -mtime +1 -execdir rmdir -- {} \; \
+#	    >/dev/null 2>&1; }
+#fi
 
-# XXX should go away/be replaced by nvi version
-if [ -d /var/preserve -a ! -h /var/preserve ]; then
-	cd /var/preserve && {
-	find . ! -name . -mtime +7 -exec rm -f -- {} \; ; }
-fi
-
-if [ -d /var/rwho -a ! -h /var/rwho ] ; then
+if [ -d /var/rwho -a ! -L /var/rwho ] ; then
 	cd /var/rwho && {
-	find . ! -name . -mtime +7 -exec rm -f -- {} \; ; }
+	find . ! -name . -mtime +7 -execdir rm -f -- {} \; ; }
 fi
 
-cd /tmp
-TMP=daily.$$
-find / \( ! -fstype local -o -fstype rdonly -o -fstype fdesc \
-		-o -fstype kernfs -o -fstype procfs \) -a -prune -o \
-	-name 'lost+found' -a -prune -o \
-	-name '*.core' -a -print -o \
-	\( -name '[#,]*' -o -name '.#*' -o -name a.out \
-	   -o -name '*.CKP' -o -name '.emacs_[0-9]*' \) \
-		-a -atime +3 -exec rm -f -- {} \; -a -print > $TMP
+#find / \( ! -fstype local -o -fstype rdonly \
+#		-o -fstype procfs \) -a -prune -o \
+#	-name 'lost+found' -a -prune -o \
+#	-name '*.core' -a -print -o \
+#	\( -name '[#,]*' -o -name '.#*' -o -name a.out \
+#	   -o -name '*.CKP' -o -name '.emacs_[0-9]*' \) \
+#		-a -atime +3 -a -execdir rm -f -- {} \; -a -print > $TMP
 
-echo ""
-echo "Possible core dumps:"
-egrep '\.core' $TMP
+if egrep -q '\.core$' $TMP; then
+	echo ""
+	echo "Possible core dumps:"
+	egrep '\.core$' $TMP
+fi
 
-echo ""
-echo "Deleted files:"
-egrep -v '\.core' $TMP
+if egrep -qv '\.core$' $TMP; then
+	echo ""
+	echo "Deleted files:"
+	egrep -v '\.core$' $TMP
+fi
 
-rm -f $TMP
-
-msgs -c
-
-if [ -f /etc/news.expire ]; then
-	/etc/news.expire
+if [ -d /var/msgs -a ! -L /var/msgs ]; then
+	msgs -c
 fi
 
 if [ -f /var/account/acct ]; then
-	echo "" ;
-	echo "Purging accounting records:" ;
-	mv /var/account/acct.2 /var/account/acct.3 ;
-	mv /var/account/acct.1 /var/account/acct.2 ;
-	mv /var/account/acct.0 /var/account/acct.1 ;
-	cp /var/account/acct /var/account/acct.0 ;
-	sa -sq ;
+	echo ""
+	echo "Purging accounting records:"
+	mv -f /var/account/acct.2 /var/account/acct.3
+	mv -f /var/account/acct.1 /var/account/acct.2
+	mv -f /var/account/acct.0 /var/account/acct.1
+	cp -f /var/account/acct /var/account/acct.0
+	sa -sq
 fi
 
-echo ""
-echo "Running calendar:"
-calendar -a
+# If ROOTBACKUP is set to 1 in the environment, and
+# if filesystem named /altroot is type ffs, on /dev/* and mounted "xx",
+# use it as a backup root filesystem to be updated daily.
+[ "X$ROOTBACKUP" = X1 ] && {
+	rootdev=`df -n / | awk '/^\/dev\// { print substr($1, 6) }'`
+	rootbak=`awk '$2 == "/altroot" && $1 ~ /^\/dev\// && $3 == "ffs" && \
+	    $4 ~ /xx/ \
+		{ print substr($1, 6) }' < /etc/fstab`
+	[ X$rootdev != X -a X$rootbak != X -a X$rootdev != X$rootbak ] && {
+		sync
+		echo ""
+		echo "Backing up root filesystem:"
+		echo "copying /dev/r$rootdev to /dev/r$rootbak"
+		dd if=/dev/r$rootdev of=/dev/r$rootbak bs=16b seek=1 skip=1 \
+			conv=noerror
+		fsck -y /dev/r$rootbak
+	}
+}
 
 # Rotation of mail log now handled automatically by cron and 'newsyslog'
 
-if [ -d /var/spool/uucp -a -f /etc/uuclean.daily ]; then
-	echo ""
-	echo "Cleaning up UUCP:"
-	echo /etc/uuclean.daily | su daemon
-fi
-
-echo ""
 echo ""
 echo "Checking subsystem status:"
 echo ""
 echo "disks:"
-df -k
+df -kl
 echo ""
 dump W
 echo ""
 
-
-echo ""
-echo "mail:"
-mailq
-
-if [ -d /var/spool/uucp ]; then
+mailq > $TMP
+if ! grep -q "^/var/spool/mqueue is empty$" $TMP; then
 	echo ""
-	echo "uucp:"
-	uustat -a
+	echo "mail:"
+	cat $TMP
 fi
 
 echo ""
 echo "network:"
-netstat -i
+netstat -ivn
 echo ""
-ruptime
 
-echo ""
-echo "Checking filesystems:"
-fsck -n | grep -v '^\*\* Phase'
-
-echo ""
-if [ -f /etc/Distfile ]; then
-	echo "Running rdist:"
-	rdist -f /etc/Distfile
+t=/var/rwho/*
+if [ "$t" != '/var/rwho/*' ]; then
+	echo ""
+	ruptime
 fi
 
-sh /etc/security 2>&1 | mail -s "daily insecurity output" root
+echo ""
+if [ -d /var/yp/binding -a ! -d /var/yp/`domainname` -o "X$CALENDAR" = X0 ]
+then
+	if [ "X$CALENDAR" = X0 ]; then
+		echo "Not running calendar, (disabled)."
+	else
+		echo "Not running calendar, (yp client)."
+	fi
+else
+	echo "Running calendar in the background."
+	calendar -a &
+fi
+
+# If CHECKFILESYSTEMS is set to 1 in the environment, run fsck
+# with the no-write flag.
+[ "X$CHECKFILESYSTEMS" = X1 ] && {
+	echo ""
+	echo "Checking filesystems:"
+	fsck -n | grep -v '^\*\* Phase'
+}
+
+if [ -f /etc/Distfile ]; then
+	echo ""
+	echo "Running rdist:"
+	if [ -d /var/log/rdist ]; then
+		logf=`date +%Y.%b.%e`
+		rdist -f /etc/Distfile 2>&1 | tee /var/log/rdist/$logf
+	else
+		rdist -f /etc/Distfile
+	fi
+fi
+
+sh /etc/security 2>&1 > $OUT
+if [ -s $OUT ]; then
+    mail -s "`hostname` daily insecurity output" root < $OUT
+fi
diff --git a/regress/lib/libpthread/Makefile b/regress/lib/libpthread/Makefile
--- a/regress/lib/libpthread/Makefile
+++ b/regress/lib/libpthread/Makefile
@@ -1,14 +1,44 @@
-# $OpenBSD$
+# $OpenBSD: Makefile,v 1.23 2004/07/10 06:44:51 david Exp $
 
-SUBDIR= cancel close cwd execve fork group netdb poll \
-	preemption pthread_cond_timedwait pthread_create \
-	pthread_join pthread_mutex readdir select setjmp signal \
-	sigsuspend sigwait sleep socket stdarg stdio switch
+SUBDIR= cancel cancel2 close closefrom cwd execve fork group \
+	malloc_duel netdb pcap poll \
+	preemption preemption_float \
+	pthread_atfork pthread_cond_timedwait pthread_create \
+	pthread_join pthread_kill pthread_mutex pthread_specific readdir \
+	select setjmp signal sigdeliver siginfo signodefer sigsuspend \
+	sigwait sleep socket stdarg stdio switch system
 
-# Not available or disabled: fcntl, pause, preemption_float and pw
-
-regress: _SUBDIRUSE
+# Not available or disabled: fcntl, getaddrinfo, pause, pw, sigmask, stdfiles
 
 install:
+
+.PHONY: testall
+testall:
+	rm -f /tmp/thread-{shared,static,debug}
+	make cleandir && make obj && make depend && \
+	REGRESS_LOG=/tmp/thread-shared make
+	(export LDFLAGS=-static; make clean && \
+	 REGRESS_LOG=/tmp/thread-static make)
+	(export DEBUG=-g; make clean && \
+	 REGRESS_LOG=/tmp/thread-debug make)
+	@echo "\n\nTest Results:"
+	@(shared=$$(grep FAIL /tmp/thread-shared) || true; \
+	  if [ "$$shared" ]; then \
+	     echo "** SHARED lib failures:"; echo "$$shared"; echo; \
+	  else \
+	     echo "No SHARED lib failures"; \
+	  fi)
+	@(static=$$(grep FAIL /tmp/thread-static) || true; \
+	  if [ "$$static" ]; then \
+	     echo "** STATIC lib failures:"; echo "$$static"; echo; \
+	  else \
+	     echo "No STATIC lib failures"; \
+	  fi)
+	@(debug=$$(grep FAIL /tmp/thread-debug) || true; \
+	  if [ "$$debug" ]; then \
+	     echo "** DEBUG lib failures:"; echo "$$debug"; echo; \
+	  else \
+	     echo "No DEBUG lib failures"; \
+	  fi)
 
 .include <bsd.subdir.mk>
