MFC: Correctly handle a ClientHello that contains no TLS extensions, rather than treating it as invalid and aborting the handshake.

diff --git a/etc/rc b/etc/rc
--- a/etc/rc
+++ b/etc/rc
@@ -1,35 +1,207 @@
-#	$NetBSD: rc,v 1.54 1995/10/08 18:11:43 thorpej Exp $
-#	from: @(#)rc	8.2 (Berkeley) 3/17/94
+#	$OpenBSD: rc,v 1.454 2015/07/20 06:59:39 rpe Exp $
 
-# System startup script run by init on autoboot
-# or after single-user.
-# Output and error are redirected to console by init,
-# and the console is the controlling terminal.
+# System startup script run by init on autoboot or after single-user.
+# Output and error are redirected to console by init, and the console is the
+# controlling terminal.
 
-stty status '^T'
+# Turn off Strict Bourne shell.
+set +o sh
 
-# Set shell to ignore SIGINT (2), but not children;
-# shell catches SIGQUIT (3) and returns to single user after fsck.
-trap : 2
-trap : 3	# shouldn't be needed
+# Subroutines (have to come first).
 
-HOME=/; export HOME
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
-export PATH
 
-# Configure ccd devices.
-if [ -f /etc/ccd.conf ]
-then
-	ccdconfig -C
-fi
+# Strip comments (and leading/trailing whitespace if IFS is set) from a file
+# and spew to stdout.
+stripcom() {
+	local _file="$1"
+	local _line
 
-if [ -e /fastboot ]
-then
-	echo "Fast boot: skipping disk checks."
-elif [ $1x = autobootx ]
-then
-	echo "Automatic boot in progress: starting file system checks."
-	fsck -p
+	{
+		while read _line ; do
+			_line=${_line%%#*}		# strip comments
+			[ -z "$_line" ] && continue
+			echo $_line
+		done
+	} <$_file
+}
+
+# Update resource limits when sysctl changes.
+# Usage: update_limit -X loginconf_name
+update_limit() {
+	local _fl="$1"	# ulimit flag
+	local _lc="$2"	# login.conf name
+	local _new _suf
+
+	for _suf in "" -cur -max; do
+		_new=`getcap -f /etc/login.conf -s ${_lc}${_suf} daemon 2>/dev/null`
+		if [ X"$_new" != X"" ]; then
+			if [ X"$_new" = X"infinity" ]; then
+				_new=unlimited
+			fi
+			case "$_suf" in
+			-cur)
+				ulimit -S $_fl $_new
+				;;
+			-max)
+				ulimit -H $_fl $_new
+				;;
+			*)
+				ulimit $_fl $_new
+				return
+				;;
+			esac
+		fi
+	done
+}
+
+# Apply sysctl(8) settings.
+sysctl_conf() {
+	[ -s /etc/sysctl.conf ] || return
+
+	# delete comments and blank lines
+	set -- `stripcom /etc/sysctl.conf`
+	while [ $# -ge 1 ] ; do
+		sysctl $1
+		# update limits if needed
+		case $1 in
+		kern.maxproc=*)
+			update_limit -p maxproc
+			;;
+		kern.maxfiles=*)
+			update_limit -n openfiles
+			;;
+		esac
+		shift
+	done
+}
+
+# Apply mixerctl(1) settings.
+mixerctl_conf() {
+	[ -s /etc/mixerctl.conf ] || return
+
+	# delete comments and blank lines
+	set -- `stripcom /etc/mixerctl.conf`
+	while [ $# -ge 1 ] ; do
+		mixerctl -q $1 >/dev/null 2>&1
+		shift
+	done
+}
+
+# Apply wscons system driver settings using wsconsctl(8).
+wsconsctl_conf() {
+	local save_IFS="$IFS"
+
+	[ -x /sbin/wsconsctl -a -s /etc/wsconsctl.conf ] || return
+	# delete comments and blank lines
+	IFS="
+"
+	set -- `stripcom /etc/wsconsctl.conf`
+	IFS="$save_IFS"
+	while [ $# -ge 1 ] ; do
+		eval wsconsctl $1
+		shift
+	done
+}
+
+random_seed() {
+	# push the old seed into the kernel
+	dd if=/var/db/host.random of=/dev/random bs=65536 count=1 status=none
+	chmod 600 /var/db/host.random
+	# ... and create a future seed
+	dd if=/dev/random of=/var/db/host.random bs=65536 count=1 status=none
+	# and create a seed file for the boot-loader
+	dd if=/dev/random of=/etc/random.seed bs=512 count=1 status=none
+	chmod 600 /etc/random.seed
+}
+
+# Populate net.inet.(tcp|udp).baddynamic with the contents of /etc/services so
+# as to avoid randomly allocating source ports that correspond to well-known
+# services.
+fill_baddynamic() {
+	local _service=$1
+	local _sysctl="net.inet.${_service}.baddynamic"
+	stripcom /etc/services |
+	{
+		# Variables are local
+		while IFS=" 	/" read _name _port _srv _junk; do
+			[ "x${_srv}" = "x${_service}" ] || continue
+			_ban="${_ban:+${_ban},}+${_port}"
+			# Flush before argv gets too long
+			if [ ${#_ban} -gt 1024 ]; then
+				sysctl -q ${_sysctl}=${_ban}
+				_ban=""
+			fi
+		done
+		[ "${_ban}" ] && sysctl -q ${_sysctl}=${_ban}
+	}
+}
+
+# Start daemon using the rc.d daemon control scripts.
+# Usage: start_daemon daemon1 daemon2 daemon3
+start_daemon() {
+	local _n
+	for _n; do
+		eval _do=\${${_n}_flags}
+		if [ X"${_do}" != X"NO" ]; then
+			/etc/rc.d/${_n} start
+		fi
+	done
+}
+
+# Generate keys for isakmpd, iked and sshd if the don't exist yet.
+make_keys() {
+	if [ ! -f /etc/isakmpd/private/local.key ]; then
+		echo -n "openssl: generating isakmpd/iked RSA key... "
+		if openssl genrsa -out /etc/isakmpd/private/local.key 2048 \
+		    >/dev/null 2>&1; then
+			chmod 600 /etc/isakmpd/private/local.key
+			openssl rsa -out /etc/isakmpd/local.pub -in \
+			    /etc/isakmpd/private/local.key -pubout \
+			    >/dev/null 2>&1
+			echo done.
+		else
+			echo failed.
+		fi
+	fi
+
+	if [ ! -f /etc/iked/private/local.key ]; then
+		# Just copy the generated isakmpd key
+		cp /etc/isakmpd/private/local.key /etc/iked/private/local.key
+		chmod 600 /etc/iked/private/local.key
+		cp /etc/isakmpd/local.pub /etc/iked/local.pub
+	fi
+
+	ssh-keygen -A
+}
+
+# Create Unix sockets directories for X if needed and make sure they have
+# correct permissions.
+setup_X_sockets() {
+	if [ -d /usr/X11R6/lib ]; then
+		for d in /tmp/.X11-unix /tmp/.ICE-unix ; do
+			if [ -d $d ]; then
+				if [ `ls -ld $d | cut -d' ' -f4` \
+				    != root ]; then
+					chown root $d
+				fi
+				if [ `ls -ld $d | cut -d' ' -f1` \
+				    != drwxrwxrwt ]; then
+					chmod 1777 $d
+				fi
+			elif [ -e $d ]; then
+				echo "Error: $d exists and isn't a directory."
+			else
+				mkdir -m 1777 $d
+			fi
+		done
+	fi
+}
+
+# Check filesystems, optionally by using a flag for fsck(8) passed as $1.
+do_fsck() {
+	local _flags=$1
+
+	fsck -p $_flags
 	case $? in
 	0)
 		;;
@@ -51,7 +223,7 @@ then
 		exit 1
 		;;
 	130)
-		# interrupt before catcher installed
+		# Interrupt before catcher installed.
 		exit 1
 		;;
 	*)
@@ -59,184 +231,312 @@ then
 		exit 1
 		;;
 	esac
+}
+
+# End subroutines.
+
+stty status '^T'
+
+# Set shell to ignore SIGINT (2), but not children; shell catches SIGQUIT (3)
+# and returns to single user after fsck.
+trap : 2
+trap : 3	# Shouldn't be needed.
+
+HOME=/; export HOME
+INRC=1; export INRC
+PATH=/sbin:/bin:/usr/sbin:/usr/bin
+export PATH
+
+# Must set the domainname before rc.conf, so YP startup choices can be made.
+if [ -f /etc/defaultdomain ]; then
+	domainname `stripcom /etc/defaultdomain`
+fi
+
+# Need to get local functions from rc.subr.
+FUNCS_ONLY=1 . /etc/rc.d/rc.subr
+
+# Load rc.conf into scope.
+_rc_parse_conf
+
+if [ X"$1" = X"shutdown" ]; then
+	if echo 2>/dev/null >>/var/db/host.random || \
+	    echo 2>/dev/null >>/etc/random.seed; then
+		random_seed
+	else
+		echo warning: cannot write random seed to disk
+	fi
+
+	# If we are in secure level 0, assume single user mode.
+	if [ `sysctl -n kern.securelevel` -ne 0 ]; then
+		pkg_scripts=${pkg_scripts%%*( )}
+		if [ -n "${pkg_scripts}" ]; then
+			echo -n 'stopping package daemons:'
+			while [ -n "${pkg_scripts}" ]; do
+				_r=${pkg_scripts##* }
+				pkg_scripts=${pkg_scripts%%*( )${_r}}
+				[ -x /etc/rc.d/${_r} ] && /etc/rc.d/${_r} stop
+			done
+			echo '.'
+		fi
+
+		[ -f /etc/rc.shutdown ] && sh /etc/rc.shutdown
+	else
+		echo single user: not running shutdown scripts
+	fi
+
+	# Bring carp interfaces down gracefully.
+	ifconfig | while read a b; do
+		case $a in
+		carp+([0-9]):) ifconfig ${a%:} down ;;
+		esac
+	done
+
+	exit 0
+fi
+
+swapctl -A -t blk
+
+if [ -e /fastboot ]; then
+	echo "Fast boot: skipping disk checks."
+elif [ X"$1" = X"autoboot" ]; then
+	echo "Automatic boot in progress: starting file system checks."
+	do_fsck
 fi
 
 trap "echo 'Boot interrupted.'; exit 1" 3
 
-swapon -a
-
 umount -a >/dev/null 2>&1
-mount -a -t nonfs
+mount -a -t nonfs,vnd
+mount -uw /		# root on nfs requires this, others aren't hurt.
 rm -f /fastboot		# XXX (root now writeable)
 
-# set flags on ttys.  (do early, in case they use tty for SLIP in netstart)
+# Set flags on ttys.  (Do early, in case they use tty for SLIP in netstart.)
 echo 'setting tty flags'
 ttyflags -a
 
-# set hostname, turn on network
+if [ -f /sbin/kbd -a -f /etc/kbdtype ]; then
+	kbd `cat /etc/kbdtype`
+fi
+
+wsconsctl_conf
+
+if [ X"${pf}" != X"NO" ]; then
+	RULES="block all"
+	RULES="$RULES\npass on lo0"
+	RULES="$RULES\npass in proto tcp from any to any port ssh keep state"
+	RULES="$RULES\npass out proto { tcp, udp } from any to any port domain keep state"
+	RULES="$RULES\npass out inet proto icmp all icmp-type echoreq keep state"
+	RULES="$RULES\npass out inet proto udp from any port bootpc to any port bootps"
+	RULES="$RULES\npass in inet proto udp from any port bootps to any port bootpc"
+	if ifconfig lo0 inet6 >/dev/null 2>&1; then
+		RULES="$RULES\npass out inet6 proto icmp6 all icmp6-type neighbrsol"
+		RULES="$RULES\npass in inet6 proto icmp6 all icmp6-type neighbradv"
+		RULES="$RULES\npass out inet6 proto icmp6 all icmp6-type routersol"
+		RULES="$RULES\npass in inet6 proto icmp6 all icmp6-type routeradv"
+		RULES="$RULES\npass out inet6 proto udp from any port dhcpv6-client to any port dhcpv6-server"
+		RULES="$RULES\npass in inet6 proto udp from any port dhcpv6-server to any port dhcpv6-client"
+	fi
+	RULES="$RULES\npass in proto carp keep state (no-sync)"
+	RULES="$RULES\npass out proto carp !received-on any keep state (no-sync)"
+	case `sysctl vfs.mounts.nfs 2>/dev/null` in
+	*[1-9]*)
+		# Don't kill NFS.
+		RULES="set reassemble yes no-df\n$RULES"
+		RULES="$RULES\npass in proto { tcp, udp } from any port { sunrpc, nfsd } to any"
+		RULES="$RULES\npass out proto { tcp, udp } from any to any port { sunrpc, nfsd } !received-on any"
+		;;
+	esac
+	echo $RULES | pfctl -f -
+	pfctl -e
+fi
+
+# Fill net.inet.(tcp|udp).baddynamic lists from /etc/services.
+fill_baddynamic udp
+fill_baddynamic tcp
+
+sysctl_conf
+
+# Set hostname, turn on network.
 echo 'starting network'
-. /etc/netstart
+ifconfig -g carp carpdemote 128
+if [ -f /etc/resolv.conf.save ]; then
+	mv -f /etc/resolv.conf.save /etc/resolv.conf
+	touch /etc/resolv.conf
+fi
+sh /etc/netstart
+dmesg >/dev/random	# Any write triggers a rekey.
 
-mount /usr >/dev/null 2>&1
-mount /var >/dev/null 2>&1
+# Load pf rules and bring up pfsync interface.
+if [ X"${pf}" != X"NO" ]; then
+	if [ -f /etc/pf.conf ]; then
+		pfctl -f /etc/pf.conf
+	fi
+	# Bring up pfsync after the working ruleset has been loaded.
+	if [ -f /etc/hostname.pfsync0 ]; then
+		sh /etc/netstart pfsync0
+	fi
+fi
 
-# clean up left-over files
-rm -f /etc/nologin
-rm -f /var/spool/lock/LCK.*
-rm -f /var/spool/uucp/STST/*
+mount -s /usr >/dev/null 2>&1
+mount -s /var >/dev/null 2>&1
+
+random_seed
+
+# Clean up left-over files.
+rm -f /etc/nologin /var/spool/lock/LCK.* /var/spool/uucp/STST/*
 (cd /var/run && { rm -rf -- *; install -c -m 664 -g utmp /dev/null utmp; })
+(cd /var/authpf && rm -rf -- *)
 
-echo -n 'starting rpc daemons:'
-echo -n ' portmap';		portmap
+# Save a copy of the boot messages.
+dmesg >/var/run/dmesg.boot
 
-if [ -f /usr/sbin/ypbind -a -d /var/yp ]; then
-	echo -n ' ypbind';		ypbind
-fi
+make_keys
 
-# $nfs_server is imported from /etc/netstart;
-# if $nfs_server == YES, the machine is setup for being an nfs server
-if [ X${nfs_server} = X"YES" -a -r /etc/exports ]; then
-	rm -f /var/db/mountdtab	
-	echo -n > /var/db/mountdtab
-	echo -n ' mountd';		mountd
-	echo -n ' nfsd';		nfsd -tun 4
-fi
-
-# $nfs_client is imported from /etc/netstart;
-# if $nfs_client == YES, the machine is setup for being an nfs client
-if [ X${nfs_client} = X"YES" ]; then
-	echo -n ' nfsiod';		nfsiod -n 4
-fi
-
-if [ X${amd} = X"YES" -a -d ${amd_dir} -a -r ${amd_master} ]; then
-	echo -n ' amd'
-	amd -l syslog -x error,noinfo,nostats -p \
-	    -a ${amd_dir} `cat ${amd_master}` > /var/run/amd.pid
-fi
-
-echo '.'
-mount -a -t nfs
-
-echo -n 'starting system logger'
-rm -f /dev/log
-syslogd
-
-# $timed_flags is imported from /etc/netstart;
-# if $timed_flags == NO, timed isn't run.
-if [ "X${timed_flags}" != X"NO" ]; then
-	echo -n ', time daemon'; timed $timed_flags
-fi
+echo -n 'starting early daemons:'
+start_daemon syslogd ldattach pflogd nsd unbound ntpd
+start_daemon iscsid isakmpd iked sasyncd ldapd npppd
 echo '.'
 
-# /var/crash should be a directory or a symbolic link
-# to the crash directory if core dumps are to be saved.
+# Load IPsec rules.
+if [ X"${ipsec}" != X"NO" ]; then
+	if [ -f /etc/ipsec.conf ]; then
+		ipsecctl -f /etc/ipsec.conf
+	fi
+fi
+
+echo -n 'starting RPC daemons:'
+start_daemon portmap ypldap
+if [ X"`domainname`" != X"" ]; then
+	start_daemon ypserv ypbind yppasswdd
+fi
+start_daemon mountd nfsd lockd statd amd
+echo '.'
+
+mount -a
+swapctl -A -t noblk
+
+# Check and mount networked filesystems.
+do_fsck -N
+mount -a -N
+
+# /var/crash should be a directory or a symbolic link to the crash directory
+# if core dumps are to be saved.
 if [ -d /var/crash ]; then
-	echo checking for core dump...
-	savecore /var/crash
+	savecore ${savecore_flags} /var/crash
 fi
 
-				echo -n 'checking quotas:'
-quotacheck -a
-				echo ' done.'
-quotaon -a
+if [ X"${check_quotas}" = X"YES" ]; then
+	echo -n 'checking quotas:'
+	quotacheck -a
+	echo ' done.'
+	quotaon -a
+fi
 
-# build ps databases
-echo 'building databases...'
-kvm_mkdb /netbsd
+kvm_mkdb			# build kvm(3) databases
 dev_mkdb
+chmod 666 /dev/tty[pqrstuvwxyzPQRST]*
+chown root:wheel /dev/tty[pqrstuvwxyzPQRST]*
 
-chmod 666 /dev/tty[pqrs]*
-
-# check the password temp/lock file
-if [ -f /etc/ptmp ]
-then
+# Check the password temp/lock file.
+if [ -f /etc/ptmp ]; then
 	logger -s -p auth.err \
-	'password file may be incorrect -- /etc/ptmp exists'
-fi
-
-virecovery=/var/tmp/vi.recover/recover.*
-if [ "$virecovery" != "/var/tmp/vi.recover/recover.*" ]; then
-	echo preserving editor files
-	for i in $virecovery; do
-		sendmail -t < $i
-	done
+	    'password file may be incorrect -- /etc/ptmp exists'
 fi
 
 echo clearing /tmp
 
-# prune quickly with one rm, then use find to clean up /tmp/[lq]*
-# (not needed with mfs /tmp, but doesn't hurt there...)
-(cd /tmp && rm -rf [a-km-pr-zA-Z]* &&
-    find . ! -name . ! -name lost+found ! -name quota.user \
-	! -name quota.group -exec rm -rf -- {} \; -type d -prune)
+# Prune quickly with one rm, then use find to clean up /tmp/[lqv]*
+# (not needed with mfs /tmp, but doesn't hurt there...).
+(cd /tmp && rm -rf [a-km-pr-uw-zA-Z]*)
+(cd /tmp &&
+    find . -maxdepth 1 ! -name . ! -name lost+found ! -name quota.user \
+	! -name quota.group ! -name vi.recover -execdir rm -rf -- {} \;)
 
-if [ -f /var/account/acct ]; then
-	echo 'turning on accounting';	accton /var/account/acct
+setup_X_sockets
+
+[ -f /etc/rc.securelevel ] && sh /etc/rc.securelevel
+# rc.securelevel did not specifically set -1 or 2, so select the default: 1.
+if [ `sysctl -n kern.securelevel` -eq 0 ]; then
+	sysctl kern.securelevel=1
 fi
 
-echo -n standard daemons:
-echo -n ' update';		update
-echo -n ' cron';		cron
+# Patch /etc/motd.
+if [ ! -f /etc/motd ]; then
+	install -c -o root -g wheel -m 664 /dev/null /etc/motd
+fi
+if T=`mktemp /tmp/_motd.XXXXXXXXXX`; then
+	sysctl -n kern.version | sed 1q >$T
+	echo "" >>$T
+	sed '1,/^$/d' </etc/motd >>$T
+	cmp -s $T /etc/motd || cp $T /etc/motd
+	rm -f $T
+fi
+
+if [ X"${accounting}" = X"YES" ]; then
+	if [ ! -f /var/account/acct ]; then
+		touch /var/account/acct
+	fi
+	echo 'turning on accounting'; accton /var/account/acct
+fi
+
+if [ -f /sbin/ldconfig ]; then
+	echo 'creating runtime link editor directory cache.'
+	if [ -d /usr/local/lib ]; then
+		shlib_dirs="/usr/local/lib $shlib_dirs"
+	fi
+	if [ -d /usr/X11R6/lib ]; then
+		shlib_dirs="/usr/X11R6/lib $shlib_dirs"
+	fi
+	ldconfig $shlib_dirs
+fi
+
+echo 'preserving editor files.'; /usr/libexec/vi.recover
+
+echo -n 'starting network daemons:'
+start_daemon ldomd sshd snmpd ldpd ripd ospfd ospf6d bgpd ifstated
+start_daemon relayd dhcpd dhcrelay mrouted dvmrpd radiusd
+
+if ifconfig lo0 inet6 >/dev/null 2>&1; then
+	fw=`sysctl -n net.inet6.ip6.forwarding`
+	if [ X"${fw}" = X"1" ]; then
+		start_daemon route6d rtadvd
+	fi
+fi
+
+start_daemon hostapd lpd smtpd slowcgi httpd ftpd
+start_daemon ftpproxy tftpd tftpproxy identd inetd rarpd bootparamd
+start_daemon rbootd mopd spamd spamlogd sndiod
 echo '.'
 
-echo -n starting network daemons:
+# If rc.firsttime exists, run it just once, and make sure it is deleted.
+if [ -f /etc/rc.firsttime ]; then
+	mv /etc/rc.firsttime /etc/rc.firsttime.run
+	. /etc/rc.firsttime.run 2>&1 | tee /dev/tty |
+		mail -Es "`hostname` rc.firsttime output" root >/dev/null
+fi
+rm -f /etc/rc.firsttime.run
 
-# $gated and $routed_flags are imported from /etc/netstart.
-# If $gated == YES, gated is used; otherwise routed.
-# If $routed_flags == NO, routed isn't run.
-if [ X${gated} = X"YES" -a -r /etc/gated.conf ]; then
-	echo -n ' gated';		gated $gated_flags
-elif [ "X${routed_flags}" != X"NO" ]; then
-	echo -n ' routed';		routed $routed_flags
+# Run rc.d(8) scripts from packages.
+if [ -n "${pkg_scripts}" ]; then
+	echo -n 'starting package daemons:'
+	for _r in $pkg_scripts; do
+		if [ -x /etc/rc.d/${_r} ]; then
+			start_daemon ${_r}
+		else
+			echo -n " ${_r}(absent)"
+		fi
+	done
+	echo '.'
 fi
 
-# $name_flags is imported from /etc/netstart;
-# if $named_flags != NO, named is run.
-if [ "X${named_flags}" != X"NO" ]; then
-	echo -n ' named';		named $named_flags
-fi
+[ -f /etc/rc.local ] && sh /etc/rc.local
 
-# $rwhod is imported from /etc/netstart;
-# if $rwhod == YES, rwhod is run.
-if [ X${rwhod} = X"YES" ]; then
-	echo -n ' rwhod';		rwhod
-fi
+ifconfig -g carp -carpdemote 128	# disable carp interlock
 
-echo -n ' printer';		lpd
-
-# $sendmail_flags is imported from /etc/netstart;
-# If $sendmail_flags == NO or /etc/sendmail.cf doesn't exist, then
-# sendmail isn't run.
-if [ "X${sendmail_flags}" != X"NO" -a -r /etc/sendmail.cf ]; then
-	echo -n ' sendmail';		sendmail ${sendmail_flags}
-fi
-
-echo -n ' inetd';		inetd
-
-# $rarpd_flags is imported from /etc/netstart;
-# If $rarpd_flags == NO or /etc/ethers doesn't exist, then
-# rarpd isn't run.
-if [ "X${rarpd_flags}" != X"NO" -a -r /etc/ethers ]; then
-	echo -n ' rarpd';		rarpd ${rarpd_flags}
-fi
-
-# $bootparamd_flags is imported from /etc/netstart;
-# If $bootparamd_flags == NO or /etc/bootparams doesn't exist, then
-# bootparamd isn't run.
-if [ "X${bootparamd_flags}" != X"NO" -a -r /etc/bootparams ]; then
-	echo -n ' rpc.bootparamd';	rpc.bootparamd ${bootparamd_flags}
-fi
-
-# $rbootd_flags is imported from /etc/netstart;
-# If $rbootd_flags == NO or /etc/rbootd.conf doesn't exist, then
-# rbootd isn't run.
-if [ "X${rbootd_flags}" != X"NO" -a -r /etc/rbootd.conf ]; then
-	echo -n ' rbootd';		rbootd ${rbootd_flags}
-fi
-
+mixerctl_conf
+echo -n 'starting local daemons:'
+start_daemon apmd sensorsd hotplugd watchdogd cron wsmoused xdm
 echo '.'
-
-. /etc/rc.local
 
 date
 exit 0
diff --git a/regress/sys/net/pf_divert/Makefile b/regress/sys/net/pf_divert/Makefile
--- a/regress/sys/net/pf_divert/Makefile
+++ b/regress/sys/net/pf_divert/Makefile
@@ -1,16 +1,21 @@
-#	$OpenBSD$
+#	$OpenBSD: Makefile,v 1.11 2014/08/18 22:58:19 bluhm Exp $
 
 # The following ports must be installed for the regression tests:
 # p5-IO-Socket-INET6	object interface for AF_INET and AF_INET6 domain sockets
 # p5-Socket6		Perl defines relating to AF_INET6 sockets
+#
+# Check wether all required perl packages are installed.  If some
+# are missing print a warning and skip the tests, but do not fail.
 
-
-TARGETS ?=		${ARGS}
-.if empty (TARGETS)
-ARGS !=			cd ${.CURDIR} && ls args-*.pl
+PERL_REQUIRE !=	perl -Mstrict -Mwarnings -e ' \
+    eval { require IO::Socket::INET6 } or print $@; \
+    eval { require Socket6 } or print $@; \
+'
+.if ! empty(PERL_REQUIRE)
+regress:
+	@echo "${PERL_REQUIRE}"
+	@echo install these perl packages for additional tests
 .endif
-REGRESS_TARGETS =	${TARGETS:S/^/run-regress-/}
-CLEANFILES +=		*.log ktrace.out stamp-*
 
 # Fill out these variables as you have to test divert with the pf
 # kernel running on a remote machine.  You have to specify a local
@@ -21,29 +26,64 @@ CLEANFILES +=		*.log ktrace.out stamp-*
 # local and remote.
 # You must have an anchor "regress" for the divert rules in the pf.conf
 # of the remote machine.  The kernel of the remote machine gets testet.
+#
+# Run make check-setup to see if you got the setup correct.
 
-LOCAL_ADDR ?= 10.188.50.10
-REMOTE_ADDR ?= 10.188.50.50
-FAKE_ADDR ?= 10.188.50.51
-LOCAL_ADDR6 ?= fdd7:e83e:66bc:211:fce1:baff:fed1:561f
-REMOTE_ADDR6 ?= fdd7:e83e:66bc:211:5054:ff:fe12:3450
-FAKE_ADDR6 ?= fdd7:e83e:66bc:211:5054:ff:fe12:3451
-REMOTE_SSH ?= q0
+LOCAL_ADDR ?=
+REMOTE_ADDR ?=
+FAKE_ADDR ?=
+LOCAL_ADDR6 ?=
+REMOTE_ADDR6 ?=
+FAKE_ADDR6 ?=
+REMOTE_SSH ?=
+
+.if empty (LOCAL_ADDR) || empty (REMOTE_ADDR) || empty (FAKE_ADDR) || \
+    empty (LOCAL_ADDR6) || empty (REMOTE_ADDR6) || empty (FAKE_ADDR6) || \
+    empty (REMOTE_SSH)
+regress:
+	@echo This tests needs a remote machine to operate on.
+	@echo LOCAL_ADDR REMOTE_ADDR FAKE_ADDR LOCAL_ADDR6
+	@echo REMOTE_ADDR6 FAKE_ADDR6 REMOTE_SSH are empty.
+	@echo Fill out these variables for additional tests.
+.endif
+
+# Automatically generate regress targets from test cases in directory.
+
+ARGS !=			cd ${.CURDIR} && ls args-*.pl
+TARGETS ?=		inet-args-tcp-to inet6-args-tcp-to \
+			inet-args-tcp-reply inet6-args-tcp-reply \
+			inet-args-udp-to inet6-args-udp-to \
+			inet-args-udp-reply inet6-args-udp-reply \
+			inet-args-udp-reply-to inet6-args-udp-reply-to \
+			inet-args-rip-to inet6-args-rip-to \
+			inet-args-rip-reply inet6-args-rip-reply \
+			inet-args-rip-reply-to inet6-args-rip-reply-to \
+			inet-args-icmp-to inet6-args-icmp-to \
+			inet-args-icmp-reply-to inet6-args-icmp-reply-to \
+			inet-args-icmp-reply-reuse inet6-args-icmp-reply-reuse \
+			inet-reuse-tcp inet6-reuse-tcp \
+			inet-reuse-udp inet6-reuse-udp \
+			inet-reuse-rip inet6-reuse-rip
+REGRESS_TARGETS =	${TARGETS:S/^/run-regress-/}
+CLEANFILES +=		*.log *.port ktrace.out stamp-*
 
 .MAIN: all
 
-.if make(regress) || make(all)
+.if ! empty (REMOTE_SSH)
+.if make (regress) || make (all)
 .BEGIN:
-.if empty (REMOTE_SSH)
-	@echo "remote test target host not set"; false
-.endif
 	@echo
 	${SUDO} true
-	ssh -t q0 ${SUDO} true
+	ssh -t ${REMOTE_SSH} ${SUDO} true
+.if ! empty (FAKE_ADDR) && ! empty (REMOTE_ADDR)
 	-${SUDO} route -n delete -inet -host ${FAKE_ADDR} 2>/dev/null
 	${SUDO} route -n add -inet -host ${FAKE_ADDR} ${REMOTE_ADDR}
+.endif
+.if ! empty (FAKE_ADDR6) && ! empty (REMOTE_ADDR6)
 	-${SUDO} route -n delete -inet6 -host ${FAKE_ADDR6} 2>/dev/null
 	${SUDO} route -n add -inet6 -host ${FAKE_ADDR6} ${REMOTE_ADDR6}
+.endif
+.endif
 .endif
 
 # Set variables so that make runs with and without obj directory.
@@ -62,22 +102,45 @@ PERLPATH =	${.CURDIR}/
 # diverted process is running on the remote machine reachable with
 # ssh.
 
+.for inet addr in inet ADDR inet6 ADDR6
+
 .for a in ${ARGS}
-run-regress-$a: $a
-.if !empty (LOCAL_ADDR)
-	@echo
-	time SUDO=${SUDO} perl ${PERLINC} ${PERLPATH}remote.pl inet ${LOCAL_ADDR} ${FAKE_ADDR} ${REMOTE_SSH} ${PERLPATH}$a
+run-regress-${inet}-${a:R}: ${a}
+	@echo '\n======== $@ ========'
+	time ${SUDO} SUDO=${SUDO} perl ${PERLINC} ${PERLPATH}remote.pl ${inet} ${LOCAL_${addr}} ${FAKE_${addr}} ${REMOTE_SSH} ${PERLPATH}${a}
+.endfor
+
+.for proto in tcp udp rip
+run-regress-${inet}-reuse-${proto}:
+	@echo '\n======== $@ ========'
+	time ${SUDO} SUDO=${SUDO} perl ${PERLINC} ${PERLPATH}remote.pl ${inet} ${LOCAL_${addr}} ${FAKE_${addr}} ${REMOTE_SSH} ${PERLPATH}args-${proto}-reply.pl
+	sed -n '/^connect peer:/s/.* //p' client.log >client.port
+	sed -n '/^connect sock:/s/.* //p' client.log >server.port
+.if "tcp" == ${proto}
+	${SUDO} tcpdrop ${LOCAL_${addr}} `cat client.port` ${FAKE_${addr}} `cat server.port`
 .endif
-.if !empty (LOCAL_ADDR6)
-	@echo
-	time SUDO=${SUDO} perl ${PERLINC} ${PERLPATH}remote.pl inet6 ${LOCAL_ADDR6} ${FAKE_ADDR6} ${REMOTE_SSH} ${PERLPATH}$a
+	time ${SUDO} SUDO=${SUDO} perl ${PERLINC} ${PERLPATH}remote.pl ${inet} ${LOCAL_${addr}} ${FAKE_${addr}} ${REMOTE_SSH} `cat client.port` `cat server.port` ${PERLPATH}args-${proto}-to.pl
+.if "tcp" == ${proto}
+	ssh ${REMOTE_SSH} ${SUDO} tcpdrop ${FAKE_${addr}} `cat server.port` ${LOCAL_${addr}} `cat client.port`
+.if "inet" == ${inet}
+	if ssh ${REMOTE_SSH} ${SUDO} pfctl -ss | \
+	    grep 'all ${proto} ${FAKE_${addr}}:'`cat server.port`' .. ${LOCAL_${addr}}:'`cat client.port`' '; \
+		then false; \
+	fi
+.else
+	if ssh ${REMOTE_SSH} ${SUDO} pfctl -ss | \
+	    grep 'all ${proto} ${FAKE_${addr}}\['`cat server.port`\]' .. ${LOCAL_${addr}}\['`cat client.port`'\] '; \
+		then false; \
+	fi
+.endif
 .endif
 .endfor
 
+.endfor
+
+.PHONY: syntax check-setup
+
 # make perl syntax check for all args files
-
-.PHONY: syntax
-
 syntax: stamp-syntax
 
 stamp-syntax: ${ARGS}
@@ -85,5 +148,20 @@ stamp-syntax: ${ARGS}
 	@perl -c ${PERLPATH}$a
 .endfor
 	@date >$@
+
+# Check wether the address, route and remote setup is correct
+check-setup:
+	@echo '\n======== $@ ========'
+	ping -n -c 1 ${LOCAL_ADDR}
+	ping -n -c 1 ${REMOTE_ADDR}
+	ping6 -n -c 1 ${LOCAL_ADDR6}
+	ping6 -n -c 1 ${REMOTE_ADDR6}
+	route -n get -inet ${FAKE_ADDR} | grep 'if address: ${LOCAL_ADDR}$$'
+	route -n get -inet ${FAKE_ADDR} | grep 'gateway: ${REMOTE_ADDR}$$'
+	route -n get -inet6 ${FAKE_ADDR6} | grep 'if address: ${LOCAL_ADDR6}$$'
+	route -n get -inet6 ${FAKE_ADDR6} | grep 'gateway: ${REMOTE_ADDR6}$$'
+	ssh ${REMOTE_SSH} ${SUDO} pfctl -sr | grep '^anchor "regress" all$$'
+	ssh ${REMOTE_SSH} ${SUDO} pfctl -si | grep '^Status: Enabled '
+	ssh ${REMOTE_SSH} perl -MIO::Socket::INET6 -MSocket6 -e 1
 
 .include <bsd.regress.mk>
