Pull in patch from current: Errata: The ef(4) driver will complain when adding an address with ifconfig (ifconfig: SIOCAIFADDR: Invalid argument). Fix: add missing 'break'

diff --git a/etc/security b/etc/security
--- a/etc/security
+++ b/etc/security
@@ -1,21 +1,28 @@
 #!/bin/sh -
 #
+#	$OpenBSD: security,v 1.34 2000/02/29 20:36:25 aaron Exp $
 #	from: @(#)security	8.1 (Berkeley) 6/9/93
-#	$Id: security,v 1.11 1995/01/31 16:09:45 jtc Exp $
 #
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 
 umask 077
 
-ERR=/tmp/_secure1.$$
-TMP1=/tmp/_secure2.$$
-TMP2=/tmp/_secure3.$$
-TMP3=/tmp/_secure4.$$
-LIST=/tmp/_secure5.$$
-OUTPUT=/tmp/_secure6.$$
+DIR=/tmp/_secure$$
+ERR=$DIR/_secure1
+TMP1=$DIR/_secure2
+TMP2=$DIR/_secure3
+TMP3=$DIR/_secure4
+LIST=$DIR/_secure5
+OUTPUT=$DIR/_secure6
 
-trap 'rm -f $ERR $TMP1 $TMP2 $TMP3 $LIST $OUTPUT' 0
+if ! mkdir $DIR ; then
+	printf "tmp directory %s already exists, looks like:\n" $DIR
+	ls -alF $DIR
+	exit 1
+fi
+
+trap 'rm -rf $DIR; exit 1' 0 1 2 3 13 15
 
 # Check the master password file syntax.
 MP=/etc/master.passwd
@@ -25,16 +32,27 @@ awk -F: '{
 		next;
 	}
 	if (NF != 10)
-		printf("Line %d has the wrong number of fields.\n", NR);
-	if ($1 !~ /^[A-Za-z0-9]*$/)
+		printf("Line %d has the wrong number of fields:\n%s\n", NR, $0);
+	if ($1 ~ /^[+-]/)
+		next;
+	if ($1 == "")
+		printf("Line %d has an empty login field:\n%s\n", NR, $0);
+	else if ($1 !~ /^[A-Za-z0-9][A-Za-z0-9_-]*$/)
 		printf("Login %s has non-alphanumeric characters.\n", $1);
 	if (length($1) > 8)
 		printf("Login %s has more than 8 characters.\n", $1);
 	if ($2 == "")
 		printf("Login %s has no password.\n", $1);
-	if (length($2) != 13 && ($10 ~ /.*sh$/ || $10 == ""))
-		printf("Login %s is off but still has a valid shell.\n", $1);
-	if ($3 == 0 && $1 != "root" && $1 != "toor")
+	if ($2 != "" && length($2) != 13 && ($10 ~ /.*sh$/ || $10 == "") &&
+           ($2 !~ /^\$[0-9a-f]+\$/) && ($2 != "skey")) {
+		if (system("test -s /etc/skeykeys && grep -q \"^"$1" \" /etc/skeykeys") == 0)
+			printf("Login %s is off but still has a valid shell and an entry in /etc/skeykeys.\n", $1);
+		if (system("test -d "$9" -a ! -r "$9"") == 0)
+			printf("Login %s if off but still has valid shell and home directory is unreadable\n\t by root; cannot check for existence of alternate access files.\n", $1);
+		else if (system("for file in .ssh .rhosts .shosts .klogin; do if test -e "$9"/$file; then if ((ls -ld "$9"/$file | cut -b 2-10 | grep -q r) && (test ! -O "$9"/$file)) ; then exit 1; fi; fi; done"))
+			 printf("Login %s is off but still has a valid shell and alternate access files in\n\t home directory are still readable.\n",$1);
+	}
+	if ($3 == 0 && $1 != "root")
 		printf("Login %s has a user id of 0.\n", $1);
 	if ($3 < 0)
 		printf("Login %s has a negative user id.\n", $1);
@@ -64,6 +82,10 @@ fi
 # Backup the master password file; a special case, the normal backup
 # mechanisms also print out file differences and we don't want to do
 # that because this file has encrypted passwords in it.
+if [ ! -d /var/backups ] ; then
+	mkdir /var/backups
+	chmod 700 /var/backups
+fi
 CUR=/var/backups/`basename $MP`.current
 BACK=/var/backups/`basename $MP`.backup
 if [ -s $CUR ] ; then
@@ -86,9 +108,11 @@ awk -F: '{
 		printf("Line %d is a blank line.\n", NR);
 		next;
 	}
+	if ($1 ~ /^[+-].*$/)
+		next;
 	if (NF != 4)
-		printf("Line %d has the wrong number of fields.\n", NR);
-	if ($1 !~ /^[A-za-z0-9]*$/)
+		printf("Line %d has the wrong number of fields:\n%s\n", NR, $0);
+	if ($1 !~ /^[A-za-z0-9][A-za-z0-9_-]*$/)
 		printf("Group %s has non-alphanumeric characters.\n", $1);
 	if (length($1) > 8)
 		printf("Group %s has more than 8 characters.\n", $1);
@@ -115,7 +139,7 @@ rhome=/root
 umaskset=no
 list="/etc/csh.cshrc /etc/csh.login ${rhome}/.cshrc ${rhome}/.login"
 for i in $list ; do
-	if [ -f $i ] ; then
+	if [ -s $i ] ; then
 		if egrep umask $i > /dev/null ; then
 			umaskset=yes
 		fi
@@ -124,11 +148,17 @@ for i in $list ; do
 			{ print "Root umask is group writeable" }
 		     $2 % 10 < 2 \
 			{ print "Root umask is other writeable" }' >> $OUTPUT
+		SAVE_PATH=$PATH
+		unset PATH
 		/bin/csh -f -s << end-of-csh > /dev/null 2>&1
-			unset path
 			source $i
-			/bin/ls -ldgT \$path > $TMP1
+			if (\$?path) then
+				/bin/ls -ldgT \$path > $TMP1
+			else
+				cat /dev/null > $TMP1
+			endif
 end-of-csh
+		PATH=$SAVE_PATH
 		awk '{
 			if ($10 ~ /^\.$/) {
 				print "The root path includes .";
@@ -144,7 +174,7 @@ end-of-csh
 done
 if [ $umaskset = "no" -o -s $OUTPUT ] ; then
 	printf "\nChecking root csh paths, umask values:\n$list\n"
-	if [ -s $OUTPUT ]; then
+	if [ -s $OUTPUT ] ; then
 		cat $OUTPUT
 	fi
 	if [ $umaskset = "no" ] ; then
@@ -153,11 +183,12 @@ if [ $umaskset = "no" -o -s $OUTPUT ] ; then
 fi
 
 > $OUTPUT
+> $TMP2
 rhome=/root
 umaskset=no
-list="${rhome}/.profile"
+list="/etc/profile ${rhome}/.profile"
 for i in $list; do
-	if [ -f $i ] ; then
+	if [ -s $i ] ; then
 		if egrep umask $i > /dev/null ; then
 			umaskset=yes
 		fi
@@ -166,12 +197,21 @@ for i in $list; do
 			{ print "Root umask is group writeable" } \
 		     $2 % 10 < 2 \
 			{ print "Root umask is other writeable" }' >> $OUTPUT
+		SAVE_PATH=$PATH
+		SAVE_ENV=$ENV
+		unset PATH ENV
 		/bin/sh << end-of-sh > /dev/null 2>&1
-			PATH=
 			. $i
-			list=\`echo \$PATH | /usr/bin/sed -e 's/:/ /g'\`
-			/bin/ls -ldgT \$list > $TMP1
+			if [ X"\$PATH" != "X" ]; then
+				list=\`echo \$PATH | /usr/bin/sed -e 's/:/ /g'\`
+				/bin/ls -ldgT \$list > $TMP1
+			else
+				> $TMP1
+			fi
+			echo \$ENV >> $TMP2
 end-of-sh
+		PATH=$SAVE_PATH
+		ENV=$SAVE_ENV
 		awk '{
 			if ($10 ~ /^\.$/) {
 				print "The root path includes .";
@@ -188,12 +228,59 @@ end-of-sh
 done
 if [ $umaskset = "no" -o -s $OUTPUT ] ; then
 	printf "\nChecking root sh paths, umask values:\n$list\n"
-	if [ -s $OUTPUT ]; then
+	if [ -s $OUTPUT ] ; then
 		cat $OUTPUT
 	fi
 	if [ $umaskset = "no" ] ; then
 		printf "\nRoot sh startup files do not set the umask.\n"
 	fi
+fi
+
+# A good .kshrc will not have a umask or path, that being set in .profile
+# check anyway.
+> $OUTPUT
+rhome=/root
+list="/etc/ksh.kshrc `cat $TMP2`"
+(cd $rhome
+ for i in $list; do
+	if [ -s $i ] ; then
+		egrep umask $i |
+		awk '$2 % 100 < 20 \
+			{ print "Root umask is group writeable" } \
+		     $2 % 10 < 2 \
+			{ print "Root umask is other writeable" }' >> $OUTPUT
+		if egrep PATH= $i > /dev/null ; then
+			SAVE_PATH=$PATH
+			unset PATH
+			/bin/ksh << end-of-sh > /dev/null 2>&1
+				. $i
+				if [ X"\$PATH" != "X" ]; then
+					list=\`echo \$PATH | /usr/bin/sed -e 's/:/ /g'\`
+					/bin/ls -ldgT \$list > $TMP1
+				else
+					> $TMP1
+				fi
+end-of-sh
+			PATH=$SAVE_PATH
+			awk '{
+				if ($10 ~ /^\.$/) {
+					print "The root path includes .";
+					next;
+				}
+			    }
+			    $1 ~ /^d....w/ \
+		{ print "Root path directory " $10 " is group writeable." } \
+			    $1 ~ /^d.......w/ \
+		{ print "Root path directory " $10 " is other writeable." }' \
+			< $TMP1 >> $OUTPUT
+		fi
+
+	fi
+ done
+)
+if [ -s $OUTPUT ] ; then
+	printf "\nChecking root ksh paths, umask values:\n$list\n"
+	cat $OUTPUT
 fi
 
 # Root and uucp should both be in /etc/ftpusers.
@@ -208,50 +295,66 @@ else
 	printf "\nUucp not listed in /etc/ftpusers file.\n"
 fi
 
-# Uudecode should not be in the /etc/aliases file.
-if egrep 'uudecode|decode' /etc/aliases; then
-	printf "\nThere is an entry for uudecode in the /etc/aliases file.\n"
+# Uudecode should not be in the /etc/mail/aliases file.
+if egrep 'uudecode|decode' /etc/mail/aliases; then
+	printf "\nThere is an entry for uudecode in the /etc/mail/aliases file.\n"
 fi
 
 # Files that should not have + signs.
-list="/etc/hosts.equiv /etc/hosts.lpd"
+list="/etc/hosts.equiv /etc/shosts.equiv /etc/hosts.lpd"
 for f in $list ; do
-	if egrep '\+' $f > /dev/null ; then
-		printf "\nPlus sign in $f file.\n"
+	if [ -s $f ] ; then
+		awk '{
+			if ($0 ~ /^\+@.*$/)
+				next;
+			if ($0 ~ /^\+.*$/)
+				printf("\nPlus sign in %s file.\n", FILENAME);
+		}' $f
 	fi
 done
 
-# Check for special users with .rhosts files.  Only root and toor should
-# have a .rhosts files.  Also, .rhosts files should not plus signs.
-awk -F: '$1 != "root" && $1 != "toor" && \
+# Check for special users with .rhosts/.shosts files.  Only root
+# should have .rhosts/.shosts files.  Also, .rhosts/.shosts
+# files should not have plus signs.
+awk -F: '$1 != "root" && $1 !~ /^[+-]/ && \
 	($3 < 100 || $1 == "ftp" || $1 == "uucp") \
 		{ print $1 " " $6 }' /etc/passwd |
 while read uid homedir; do
-	if [ -f ${homedir}/.rhosts ] ; then
-		rhost=`ls -ldgT ${homedir}/.rhosts`
-		printf "$uid: $rhost\n"
-	fi
+	for j in .rhosts .shosts; do
+		# Root owned .rhosts/.shosts files are ok.
+		if [ -s ${homedir}/$j -a ! -O ${homedir}/$j ] ; then
+			rhost=`ls -ldgT ${homedir}/$j`
+			printf "$uid: $rhost\n"
+		fi
+	done
 done > $OUTPUT
 if [ -s $OUTPUT ] ; then
-	printf "\nChecking for special users with .rhosts files.\n"
+	printf "\nChecking for special users with .rhosts/.shosts files.\n"
 	cat $OUTPUT
 fi
 
-awk -F: '{ print $1 " " $6 }' /etc/passwd | \
+awk -F: '/^[^+-]/ { print $1 " " $6 }' /etc/passwd | \
 while read uid homedir; do
-	if [ -f ${homedir}/.rhosts ] && \
-	    egrep '\+' ${homedir}/.rhosts > /dev/null ; then
-		printf "$uid: + in .rhosts file.\n"
-	fi
+	for j in .rhosts .shosts; do
+		if [ -s ${homedir}/$j ] ; then
+			awk '{
+				if ($0 ~ /^+@.*$/ )
+					next;
+				if ($0 ~ /^\+[ 	]*$/ )
+					printf("%s has + sign in it.\n",
+						FILENAME);
+			}' ${homedir}/$j
+		fi
+	done
 done > $OUTPUT
 if [ -s $OUTPUT ] ; then
-	printf "\nChecking .rhosts files syntax.\n"
+	printf "\nChecking .rhosts/.shosts files syntax.\n"
 	cat $OUTPUT
 fi
 
 # Check home directories.  Directories should not be owned by someone else
 # or writeable.
-awk -F: '{ print $1 " " $6 }' /etc/passwd | \
+awk -F: '/^[^+-]/ { print $1 " " $6 }' /etc/passwd | \
 while read uid homedir; do
 	if [ -d ${homedir}/ ] ; then
 		file=`ls -ldgT ${homedir}`
@@ -270,8 +373,8 @@ if [ -s $OUTPUT ] ; then
 fi
 
 # Files that should not be owned by someone else or readable.
-list=".netrc .rhosts"
-awk -F: '{ print $1 " " $6 }' /etc/passwd | \
+list=".netrc .rhosts .pgp/secring.pgp .shosts .ssh/identity .ssh/random_seed"
+awk -F: '/^[^+-]/ { print $1 " " $6 }' /etc/passwd | \
 while read uid homedir; do
 	for f in $list ; do
 		file=${homedir}/${f}
@@ -292,9 +395,12 @@ awk '$1 != $5 && $5 != "root" \
 	{ print "user " $1 " " $2 " file is other writeable" }' > $OUTPUT
 
 # Files that should not be owned by someone else or writeable.
-list=".bashrc .cshrc .emacs .exrc .forward .klogin .login .logout \
-      .profile .tcshrc"
-awk -F: '{ print $1 " " $6 }' /etc/passwd | \
+list=".bashrc .bash_profile .bash_login .bash_logout .cshrc \
+      .emacs .exrc .forward .fvwmrc .inputrc .klogin .kshrc .login \
+      .logout .nexrc .profile .screenrc .ssh .ssh/config \
+      .ssh/authorized_keys .ssh/environment .ssh/known_hosts .ssh/rc \
+      .tcshrc .twmrc .xsession .xinitrc .Xdefaults .Xauthority"
+awk -F: '/^[^+-]/ { print $1 " " $6 }' /etc/passwd | \
 while read uid homedir; do
 	for f in $list ; do
 		file=${homedir}/${f}
@@ -326,45 +432,51 @@ if [ -s $OUTPUT ] ; then
 fi
 
 # File systems should not be globally exported.
-awk '{
-	readonly = 0;
-	for (i = 2; i <= NF; ++i) {
-		if ($i ~ /-ro/)
-			readonly = 1;
-		else if ($i !~ /^-/)
+if [ -s /etc/exports ] ; then
+	awk '{
+		if (($1 ~ /^#/) || ($1 ~ /^$/))
 			next;
-	}
-	if (readonly)
-		print "File system " $1 " globally exported, read-only."
-	else
-		print "File system " $1 " globally exported, read-write."
-}' < /etc/exports > $OUTPUT
-if [ -s $OUTPUT ] ; then
-	printf "\nChecking for globally exported file systems.\n"
-	cat $OUTPUT
+		readonly = 0;
+		for (i = 2; i <= NF; ++i) {
+			if ($i ~ /^-ro$/)
+				readonly = 1;
+			else if ($i !~ /^-/)
+				next;
+		}
+		if (readonly)
+			print "File system " $1 " globally exported, read-only."
+		else
+			print "File system " $1 " globally exported, read-write."
+	}' < /etc/exports > $OUTPUT
+	if [ -s $OUTPUT ] ; then
+		printf "\nChecking for globally exported file systems.\n"
+		cat $OUTPUT
+	fi
 fi
 
-# Display any changes in setuid files and devices.
-printf "\nChecking setuid files and devices:\n"
+# Display any changes in setuid/setgid files and devices.
+pending="\nChecking setuid/setgid files and devices:\n"
 (find / \( ! -fstype local -o -fstype fdesc -o -fstype kernfs \
-		-o -fstype procfs \) -a -prune -o \
-    \( -perm -u+s -o -perm -g+s -o ! -type d -a ! -type f -a ! -type l -a \
-       ! -type s \) | \
-sort | sed -e 's/^/ls -ldgT /' | sh > $LIST) 2> $OUTPUT
+	-o -fstype procfs \) -a -prune -o \
+	-type f -a \( -perm -u+s -o -perm -g+s \) -print0 -o \
+	! -type d -a ! -type f -a ! -type l -a ! -type s -a ! -type p \
+	-print0 | xargs -0 ls -ldgT | sort +9 > $LIST) 2> $OUTPUT
 
 # Display any errors that occurred during system file walk.
 if [ -s $OUTPUT ] ; then
-	printf "Setuid/device find errors:\n"
+	printf "${pending}Setuid/device find errors:\n"
+	pending=
 	cat $OUTPUT
 	printf "\n"
 fi
 
-# Display any changes in the setuid file list.
+# Display any changes in the setuid/setgid file list.
 egrep -v '^[bc]' $LIST > $TMP1
 if [ -s $TMP1 ] ; then
 	# Check to make sure uudecode isn't setuid.
 	if grep -w uudecode $TMP1 > /dev/null ; then
-		printf "\nUudecode is setuid.\n"
+		printf "${pending}\nUudecode is setuid.\n"
+		pending=
 	fi
 
 	CUR=/var/backups/setuid.current
@@ -377,14 +489,16 @@ if [ -s $TMP1 ] ; then
 			> $TMP2
 			join -110 -210 -v2 $CUR $TMP1 > $OUTPUT
 			if [ -s $OUTPUT ] ; then
-				printf "Setuid additions:\n"
+				printf "${pending}Setuid additions:\n"
+				pending=
 				tee -a $TMP2 < $OUTPUT
 				printf "\n"
 			fi
 
 			join -110 -210 -v1 $CUR $TMP1 > $OUTPUT
 			if [ -s $OUTPUT ] ; then
-				printf "Setuid deletions:\n"
+				printf "${pending}Setuid deletions:\n"
+				pending=
 				tee -a $TMP2 < $OUTPUT
 				printf "\n"
 			fi
@@ -392,7 +506,8 @@ if [ -s $TMP1 ] ; then
 			sort +9 $TMP2 $CUR $TMP1 | \
 			    sed -e 's/[	 ][	 ]*/ /g' | uniq -u > $OUTPUT
 			if [ -s $OUTPUT ] ; then
-				printf "Setuid changes:\n"
+				printf "${pending}Setuid changes:\n"
+				pending=
 				column -t $OUTPUT
 				printf "\n"
 			fi
@@ -401,7 +516,8 @@ if [ -s $TMP1 ] ; then
 			cp $TMP1 $CUR
 		fi
 	else
-		printf "Setuid additions:\n"
+		printf "${pending}Setuid additions:\n"
+		pending=
 		column -t $TMP1
 		printf "\n"
 		cp $TMP1 $CUR
@@ -411,10 +527,10 @@ fi
 # Check for block and character disk devices that are readable or writeable
 # or not owned by root.operator.
 >$TMP1
-DISKLIST="dk fd hd hk hp jb kra ra rb rd rl rx rz sd up wd"
+DISKLIST="ccd dk fd hd hk hp jb kra ra rb rd rl rx rz sd up vnd wd xd"
 for i in $DISKLIST; do
-	egrep "^b.*/${i}[0-9][0-9]*[a-h]$"  $LIST >> $TMP1
-	egrep "^c.*/r${i}[0-9][0-9]*[a-h]$"  $LIST >> $TMP1
+	egrep "^b.*/${i}[0-9][0-9]*[B-H]?[a-p]$"  $LIST >> $TMP1
+	egrep "^c.*/r${i}[0-9][0-9]*[B-H]?[a-p]$"  $LIST >> $TMP1
 done
 
 awk '$3 != "root" || $4 != "operator" || $1 !~ /.rw-r-----/ \
@@ -481,14 +597,15 @@ fi
 # Create the mtree tree specifications using:
 #
 #	mtree -cx -pDIR -kcksum,gid,mode,nlink,size,link,time,uid > DIR.secure
-#	chown root.wheel DIR.SECURE
-#	chmod 600 DIR.SECURE
+#	chown root.wheel DIR.secure
+#	chmod 600 DIR.secure
 #
 # Note, this is not complete protection against Trojan horsed binaries, as
 # the hacker can modify the tree specification to match the replaced binary.
 # For details on really protecting yourself against modified binaries, see
 # the mtree(8) manual page.
-if cd /etc/mtree; then
+if [ -d /etc/mtree ] ; then
+	cd /etc/mtree
 	mtree -e -p / -f /etc/mtree/special > $OUTPUT
 	if [ -s $OUTPUT ] ; then
 		printf "\nChecking special files and directories.\n"
@@ -497,9 +614,10 @@ if cd /etc/mtree; then
 
 	> $OUTPUT
 	for file in *.secure; do
+		[ $file = '*.secure' ] && continue
 		tree=`sed -n -e '3s/.* //p' -e 3q $file`
 		mtree -f $file -p $tree > $TMP1
-		if [ -s $TMP1 ]; then
+		if [ -s $TMP1 ] ; then
 			printf "\nChecking $tree:\n" >> $OUTPUT
 			cat $TMP1 >> $OUTPUT
 		fi
@@ -508,16 +626,18 @@ if cd /etc/mtree; then
 		printf "\nChecking system binaries:\n"
 		cat $OUTPUT
 	fi
+else
+	echo /etc/mtree is missing
 fi
 
 # List of files that get backed up and checked for any modifications.  Each
 # file is expected to have two backups, /var/backups/file.{current,backup}.
 # Any changes cause the files to rotate.
 if [ -s /etc/changelist ] ; then
-	for file in `cat /etc/changelist`; do
+	for file in `egrep -v "^#|$MP" /etc/changelist`; do
 		CUR=/var/backups/`basename $file`.current
 		BACK=/var/backups/`basename $file`.backup
-		if [ -s $file ]; then
+		if [ -s $file ] ; then
 			if [ -s $CUR ] ; then
 				diff $CUR $file > $OUTPUT
 				if [ -s $OUTPUT ] ; then
