MFC: Fix by djm@
fix an exploitable integer overflow found by Chris Evans of Google
Security; ok deraadt

diff --git a/etc/weekly b/etc/weekly
--- a/etc/weekly
+++ b/etc/weekly
@@ -1,57 +1,44 @@
 #!/bin/sh -
 #
-#	@(#)weekly	5.14 (Berkeley) 6/23/91
+#	$OpenBSD: weekly,v 1.15 2005/11/12 16:14:37 jmc Exp $
 #
 
 PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/libexec
 export PATH
 
-host=`hostname -s`
-echo "Subject: $host weekly run output"
-
-#echo ""
-#echo "Removing old .o files:"
-#find /usr/src -name '*.o' -atime +21 -print -a -exec rm -f {} \;
-
-# see if /usr/src exists and is local
-# before looking there for checked-out files
-
-#if [ -d /usr/src -a \
-#  X"`find -f /usr/src ! -fstype local -prune -or -type d -print -prune`" != X ];
-#then
-#	echo "looking for checked out files:"
-#	TDIR=/tmp/_checkout$$
-#
-#	mkdir $TDIR
-#	for file in `find -f /usr/src ! -fstype local -prune -or \
-#	    -name 'p.*' -print | egrep 'SCCS/p\.'`; do
-#		owner=`awk '{ print $3 }' $file`
-#		echo "$owner	$file"
-#		echo $file >> $TDIR/$owner
-#	done | sed -e 's,SCCS/p.,,'
-#	for file in $TDIR/*; do
-#		sed -e 's,SCCS/p.,,' $file | \
-#		    Mail -s 'checked out files' `basename $file`
-#	done
-#	rm -rf $TDIR
-#fi
-
-if [ -f /usr/lib/uucp/clean.weekly ]; then
+if [ -f /etc/weekly.local ]; then
 	echo ""
-	echo "Cleaning up UUCP:"
-	echo /usr/lib/uucp/clean.weekly | su daemon
+	echo "Running weekly.local:"
+	. /etc/weekly.local
 fi
-echo ""
-
-# Rotation of message log now handled automatically by cron and 'newsyslog'
 
 echo ""
 if [ -f /var/db/locate.database ]; then
-	echo "Rebuilding locate database:"
-	chmod 644 /var/db/locate.database
-	chown nobody.nobody /var/db/locate.database
-	echo /usr/libexec/locate.updatedb | nice -5 su -m nobody 2>/dev/null
-	chown root.wheel /var/db/locate.database
+	TMP=`mktemp /var/db/locate.database.XXXXXXXXXX`
+	if [ $? -eq 0 ]; then
+		trap 'rm -f $TMP' 0 1 15
+		echo "Rebuilding locate database:"
+		UPDATEDB="/usr/libexec/locate.updatedb"
+		echo "${UPDATEDB} --fcodes=- --tmpdir=${TMPDIR:-/var/tmp}" | \
+		    nice -5 su -m nobody 2>/dev/null 1>$TMP
+		if [ -s "$TMP" ]; then
+			chmod 444 $TMP
+			chown root:wheel $TMP
+			mv -f $TMP /var/db/locate.database
+		else
+			echo "Not installing locate database; zero size"
+		fi
+	else
+		echo "Not rebuilding locate database; can't create temp file"
+	fi
 else
 	echo "Not rebuilding locate database; no /var/db/locate.database"
 fi
+
+echo ""
+echo "Rebuilding whatis databases:"
+makewhatis
+
+# echo ""
+# echo "Doing login accounting:"
+# ac -p | sort -nr +1
