Start 3.2-stable

diff --git a/usr.sbin/httpd/src/Configure b/usr.sbin/httpd/src/Configure
--- a/usr.sbin/httpd/src/Configure
+++ b/usr.sbin/httpd/src/Configure
@@ -1,4 +1,5 @@
 #!/bin/sh
+# $OpenBSD: Configure,v 1.18 2002/03/22 16:55:44 brad Exp $
 ## ====================================================================
 ## The Apache Software License, Version 1.1
 ##
@@ -84,6 +85,7 @@ awkfile=$tmpfile.4
 tmpconfig=$tmpfile.5
 SUBDIRS="ap main"
 APLIBDIRS=""
+SHELL=/bin/sh
 
 ####################################################################
 ## Now handle any arguments, which, for now, is -file
@@ -207,7 +209,7 @@ fi
 ## then fold in the modules that were included in Configuration
 ##
 echo "Creating Makefile"
-./helpers/mfhead . $file > Makefile
+${SHELL} helpers/mfhead . $file > Makefile
 
 ####################################################################
 ## Now we create a stub file, called Makefile.config, which
@@ -227,17 +229,17 @@ awk >Makefile.config <$tmpfile '
 ####################################################################
 ## Extract the rules.
 ##
-RULE_WANTHSREGEX=`./helpers/CutRule WANTHSREGEX $file`
-RULE_STATUS=`./helpers/CutRule STATUS $file`
-RULE_SOCKS4=`./helpers/CutRule SOCKS4 $file`
-RULE_SOCKS5=`./helpers/CutRule SOCKS5 $file`
-RULE_IRIXNIS=`./helpers/CutRule IRIXNIS $file`
-RULE_IRIXN32=`./helpers/CutRule IRIXN32 $file`
-RULE_PARANOID=`./helpers/CutRule PARANOID $file`
-RULE_EXPAT=`./helpers/CutRule EXPAT $file`
-RULE_CYGWIN_WINSOCK=`./helpers/CutRule CYGWIN_WINSOCK $file` 
-RULE_SHARED_CORE=`./helpers/CutRule SHARED_CORE $file`
-RULE_SHARED_CHAIN=`./helpers/CutRule SHARED_CHAIN $file`
+RULE_WANTHSREGEX=`${SHELL} helpers/CutRule WANTHSREGEX $file`
+RULE_STATUS=`${SHELL} helpers/CutRule STATUS $file`
+RULE_SOCKS4=`${SHELL} helpers/CutRule SOCKS4 $file`
+RULE_SOCKS5=`${SHELL} helpers/CutRule SOCKS5 $file`
+RULE_IRIXNIS=`${SHELL} helpers/CutRule IRIXNIS $file`
+RULE_IRIXN32=`${SHELL} helpers/CutRule IRIXN32 $file`
+RULE_PARANOID=`${SHELL} helpers/CutRule PARANOID $file`
+RULE_EXPAT=`${SHELL} helpers/CutRule EXPAT $file`
+RULE_CYGWIN_WINSOCK=`${SHELL} helpers/CutRule CYGWIN_WINSOCK $file` 
+RULE_SHARED_CORE=`${SHELL} helpers/CutRule SHARED_CORE $file`
+RULE_SHARED_CHAIN=`${SHELL} helpers/CutRule SHARED_CHAIN $file`
 
 ####################################################################
 ## Rule SHARED_CORE implies required DSO support
@@ -272,8 +274,8 @@ CAT="cat"
 ## As more PLATFORMs are added to Configuration.tmpl, be sure to
 ## add the required lines below.
 ##
-PLAT=`./helpers/GuessOS`
 SHELL="/bin/sh"
+PLAT=`${SHELL} helpers/GuessOS`
 OSDIR="os/unix"
 
 case "$PLAT" in
@@ -943,7 +945,7 @@ if [ "x$TCC" = "x" ]; then
 	for compilers in "gcc" "cc" "acc" "c89"
 	do
 	    lookedfor="$lookedfor $compilers"
-	    if ./helpers/PrintPath -s $compilers; then
+	    if ${SHELL} helpers/PrintPath -s $compilers; then
 		COMPILER="$compilers"
 		break
 	    fi
@@ -977,9 +979,9 @@ fi
 ##
 TCPP=`egrep '^CPP=' Makefile.config | tail -1 | awk -F= '{print $2}'`
 if [ "x$TCPP" != "x" ]; then
-    CPP=`CPP="$TCPP"; export CPP CC; ./helpers/findcpp.sh`
+    CPP=`CPP="$TCPP"; export CPP CC; ${SHELL} ./helpers/findcpp.sh`
 else
-    CPP=`export CC; ./helpers/findcpp.sh`
+    CPP=`export CC; ${SHELL} ./helpers/findcpp.sh`
 fi
 if [ "x$TCPP" = "x" ]; then
     echo "CPP=$CPP" >> Makefile.config
@@ -1007,7 +1009,7 @@ for header in $CHECK_FOR_HEADERS; do
     echo "" >>$AP_CONFIG_AUTO_H
     echo "/* check: #include <$header> */" >>$AP_CONFIG_AUTO_H
     name="`echo $header | sed -e 's:/:_:g' -e 's:\.:_:g' | tr '[a-z]' '[A-Z]'`"
-    ./helpers/checkheader.sh $header
+    ${SHELL} ./helpers/checkheader.sh $header
     if [ $? -eq 0 ]; then
 	echo "#ifndef HAVE_${name}" >>$AP_CONFIG_AUTO_H
 	echo "#define HAVE_${name} 1" >>$AP_CONFIG_AUTO_H
@@ -1025,7 +1027,7 @@ done
 # to decide whether the Processor Binding can be used or not
 case "$PLAT" in
     *-ibm-aix*)
-	CPP=$CPP ./helpers/checkheader.sh sys/processor.h
+	CPP=$CPP ${SHELL} helpers/checkheader.sh sys/processor.h
 	if [ $? -eq 0 ]; then
 	    CFLAGS="$CFLAGS -DAIX_BIND_PROCESSOR"
 	fi
@@ -1130,7 +1132,7 @@ if [ "x$using_shlib" = "x1" ] ; then
 		*)
 		   LD_SHLIB="gcc"
 		   LDFLAGS_SHLIB="-shared \$(CFLAGS_SHLIB)"
-		   if [ "x`echo __ELF__ | $CC -E - | grep __ELF__`" = "x" ]; then
+		   if [ -z "`echo __ELF__ | ${CC} -E - | grep __ELF__`" ]; then
 		     LDFLAGS_SHLIB_EXPORT="-Wl,-E"
 		   fi
 		;;
@@ -1582,7 +1584,7 @@ if [ "x$RANLIB" = "x" ]; then
     if [ "x$TRANLIB" != "x" ]; then
 	RANLIB=$TRANLIB
     else
-	if ./helpers/PrintPath -s ranlib; then
+	if ${SHELL} helpers/PrintPath -s ranlib; then
 	    RANLIB="ranlib"
 	else
 	    RANLIB="true"
@@ -1598,7 +1600,7 @@ fi
 case "$PLAT" in
     *-linux*)
 	# newer systems using glibc 2.x need -lcrypt
-	if ./helpers/TestCompile lib crypt; then
+	if ${SHELL} helpers/TestCompile lib crypt; then
 	    LIBS="$LIBS -lcrypt"
 	fi
 	;;
@@ -1606,11 +1608,11 @@ case "$PLAT" in
     *-dg-dgux*)
 	# R4.11MU02 requires -lsocket -lnsl ... no idea if it's earlier or
 	# later than what we already knew about.  PR#732
-	if ./helpers/TestCompile lib nsl; then
+	if ${SHELL} helpers/TestCompile lib nsl; then
 	    LIBS="$LIBS -lnsl"
 	    TLIB='-lnsl'
 	fi
-	if TLIB=$TLIB ./helpers/TestCompile lib socket; then
+	if TLIB=$TLIB ${SHELL} helpers/TestCompile lib socket; then
 	    LIBS="-lsocket $LIBS"
 	fi
 	;;
@@ -1628,19 +1630,19 @@ case "$PLAT" in
 	# -lnsl may be available (or may be not).
 	# In standard SVR4 systems, -lsocket relies on some symbols
 	# from -lnsl, so the test for -lnsl must appear first.
-	if ./helpers/TestCompile lib nsl; then
+	if ${SHELL} helpers/TestCompile lib nsl; then
 	    LIBS="$LIBS -lnsl"
 	    TLIB='-lnsl'
 	fi
-	if TLIB=$TLIB ./helpers/TestCompile lib socket; then
+	if TLIB=$TLIB ${SHELL} helpers/TestCompile lib socket; then
 	    LIBS="-lsocket $LIBS"
 	fi
 	# Auto-detect presence of libdl for dynamic loading
-	if ./helpers/TestCompile lib dl; then
-	    if ./helpers/TestCompile func dlopen; then
+	if ${SHELL} ./helpers/TestCompile lib dl; then
+	    if ${SHELL} ./helpers/TestCompile func dlopen; then
 		LIBS="$LIBS -ldl"
 		TLIB='-ldl'
-	    fi
+    	   fi
 	fi
 	# Test for the presence of the "union semun":
 	if TCADDINCL='#include <sys/types.h>
@@ -1651,11 +1653,11 @@ case "$PLAT" in
 	    CFLAGS="$CFLAGS -DNEED_UNION_SEMUN"
 	fi
 	# Test for the presence of the _rini_struct typedef:
-	if TCADDINCL='#include <pwd.h>' ./helpers/TestCompile sizeof _rini_struct; then
+	if TCADDINCL='#include <pwd.h>' ${SHELL} ./helpers/TestCompile sizeof _rini_struct; then
 	    CFLAGS="$CFLAGS -DHAVE_RINI_STRUCT"
 	fi
 	# Test whether initgroups() must be emulated:
-	if ./helpers/TestCompile func initgroups; then
+	if ${SHELL} helpers/TestCompile func initgroups; then
 	    :
 	else
 	    CFLAGS="$CFLAGS -DNEED_INITGROUPS"
@@ -1869,6 +1871,72 @@ if [ "x$RULE_WANTHSREGEX" = "xyes" ]; then
 fi
 
 ####################################################################
+## Extended API (EAPI) support:
+##
+if [ "x$RULE_EAPI" = "x" ]; then
+    RULE_EAPI=`${SHELL} helpers/CutRule EAPI $file`
+fi
+if [ "x$RULE_EAPI" = "xyes" ]; then
+    echo " + enabling Extended API (EAPI)"
+    CFLAGS="$CFLAGS -DEAPI"
+    #   some vendor compilers are too restrictive
+    #   for our ap_hook and ap_ctx sources.
+    case "$OS:$CC" in
+        *IRIX-32*:*/cc|*IRIX-32*:cc )
+            CFLAGS="$CFLAGS -woff 1048,1110,1164"
+            ;;
+    esac
+    #   MM Shared Memory Library support for EAPI
+    if [ "x$EAPI_MM" = "x" ]; then
+        EAPI_MM=`egrep '^EAPI_MM=' $file | sed -n -e '$p' | awk -F= '{print $2}'`
+    fi
+    if [ "x$EAPI_MM" != "x" ]; then
+        case $EAPI_MM in
+            SYSTEM|/* ) ;;
+            * ) for p in . .. ../..; do
+                    if [ -d "$p/$EAPI_MM" ]; then
+                        EAPI_MM="`echo $p/$EAPI_MM | sed -e 's;/\./;/;g'`" 
+                        break
+                    fi
+                done
+                ;;
+        esac
+        if [ "x$EAPI_MM" = "xSYSTEM" ]; then
+            echo "   using MM library for EAPI: (system-wide)"
+            CFLAGS="$CFLAGS -DEAPI_MM"
+            __INCLUDES="`mm-config --cflags`"
+            if [ "x$__INCLUDES" != "x-I/usr/include" ]; then
+                INCLUDES="$INCLUDES $__INCLUDES"
+            fi
+            LDFLAGS="$LDFLAGS `mm-config --ldflags`"
+            LIBS="$LIBS `mm-config --libs`"
+        else
+            if [ -f "$EAPI_MM/.libs/libmm.a" -a -f "$EAPI_MM/mm.h" ]; then
+                echo "   using MM library: $EAPI_MM (source-tree only)"
+                case $EAPI_MM in
+                    /* ) ;;
+                    *  ) EAPI_MM="\$(SRCDIR)/$EAPI_MM" ;;
+                esac
+                CFLAGS="$CFLAGS -DEAPI_MM"
+                INCLUDES="$INCLUDES -I$EAPI_MM"
+                LDFLAGS="$LDFLAGS -L$EAPI_MM/.libs"
+                LIBS="$LIBS -lmm"
+            elif [ -f "$EAPI_MM/bin/mm-config" ]; then
+                echo "   using MM library: $EAPI_MM (installed)"
+                CFLAGS="$CFLAGS -DEAPI_MM"
+                INCLUDES="$INCLUDES `$EAPI_MM/bin/mm-config --cflags`"
+                LDFLAGS="$LDFLAGS `$EAPI_MM/bin/mm-config --ldflags`"
+                LIBS="$LIBS `$EAPI_MM/bin/mm-config --libs`"
+            else
+                echo "Configure:Error: Cannot find MM library under $EAPI_MM" 1>&2
+                exit 1
+            fi
+        fi
+    fi
+fi
+
+
+####################################################################
 ## Add in the Expat library if needed/wanted.
 ##
 
@@ -1883,7 +1951,7 @@ if [ "x$RULE_EXPAT" = "xdefault" ]; then
 fi
 
 if [ "x$RULE_EXPAT" = "xyes" ]; then
-    if ./helpers/TestCompile lib expat; then
+    if ${SHELL} ./helpers/TestCompile lib expat; then
         echo " + using system Expat"
         LIBS="$LIBS -lexpat"
     else
@@ -1911,7 +1979,7 @@ if [ "x$using_shlib" = "x1" ] ; then
 	#   to our DSO files, i.e. PIC libraries and shared libraries
 	extra_ldflags="`grep EXTRA_LDFLAGS= Makefile.config`"
 	extra_libs="`grep EXTRA_LIBS= Makefile.config`"
-	eval "`./helpers/slo.sh $LDFLAGS $LIBS $extra_ldflags $extra_libs`"
+	eval "`${SHELL} helpers/slo.sh $LDFLAGS $LIBS $extra_ldflags $extra_libs`"
 	LIBS_SHLIB="$SLO_DIRS_PIC $SLO_LIBS_PIC $SLO_DIRS_DSO $SLO_LIBS_DSO"
     fi
 fi
@@ -2186,19 +2254,19 @@ if [ "x$using_shlib" = "x1" ] ; then
 	    esac
 	    ;;
 	*-hp-hpux*)
-	    if ./helpers/TestCompile func shl_load; then
+	    if ${SHELL} helpers/TestCompile func shl_load; then
 		:
 	    else
-		if ./helpers/TestCompile lib dld; then
+		if ${SHELL} helpers/TestCompile lib dld; then
 		    DL_LIB="-ldld"
 		fi
 	    fi
 	    ;;
 	* )
-	    if ./helpers/TestCompile func dlopen; then
+	    if ${SHELL} helpers/TestCompile func dlopen; then
 		:
 	    else
-		if ./helpers/TestCompile lib dl; then
+		if ${SHELL} helpers/TestCompile lib dl; then
 		    DL_LIB="-ldl"
 		fi
 	    fi
@@ -2216,7 +2284,7 @@ fi
 ## We check the sizeof various data types
 ##
 echo " + checking sizeof various data types"
-AP_TYPE_QUAD=`./helpers/TestCompile -r sizeof 'long long'`
+AP_TYPE_QUAD=`${SHELL} helpers/TestCompile -r sizeof 'long long'`
 if [ "x$AP_TYPE_QUAD" = "x" ]; then
     AP_TYPE_QUAD="unknown_quad"
     AP_LONGEST_LONG="long"
@@ -2235,13 +2303,13 @@ echo "#endif" >>$AP_CONFIG_AUTO_H
 ##
 ## Check for availability of isinf() and isnan()
 ##
-if ./helpers/TestCompile func isinf ; then
+if ${SHELL} ./helpers/TestCompile func isinf ; then
     echo "" >>$AP_CONFIG_AUTO_H
     echo "/* determine: isinf() found in libc */ " >>$AP_CONFIG_AUTO_H
     echo "#ifndef HAVE_ISINF" >>$AP_CONFIG_AUTO_H
     echo "#define HAVE_ISINF 1" >>$AP_CONFIG_AUTO_H
     echo "#endif" >>$AP_CONFIG_AUTO_H
-elif ./helpers/TestCompile lib m isinf ; then
+elif ${SHELL} ./helpers/TestCompile lib m isinf ; then
     echo "" >>$AP_CONFIG_AUTO_H
     echo "/* determine: isinf() found in libm */ " >>$AP_CONFIG_AUTO_H
     echo "#ifndef HAVE_ISINF" >>$AP_CONFIG_AUTO_H
@@ -2251,13 +2319,13 @@ elif ./helpers/TestCompile lib m isinf ; then
     ADDED_LM="yes"
 fi
 
-if ./helpers/TestCompile func isnan ; then
+if ${SHELL} ./helpers/TestCompile func isnan ; then
     echo "" >>$AP_CONFIG_AUTO_H
     echo "/* determine: isnan() found in libc */ " >>$AP_CONFIG_AUTO_H
     echo "#ifndef HAVE_ISNAN" >>$AP_CONFIG_AUTO_H
     echo "#define HAVE_ISNAN 1" >>$AP_CONFIG_AUTO_H
     echo "#endif" >>$AP_CONFIG_AUTO_H
-elif ./helpers/TestCompile lib m isnan ; then
+elif ${SHELL} ./helpers/TestCompile lib m isnan ; then
     echo "" >>$AP_CONFIG_AUTO_H
     echo "/* determine: isnan() found in libm */ " >>$AP_CONFIG_AUTO_H
     echo "#ifndef HAVE_ISNAN" >>$AP_CONFIG_AUTO_H
@@ -2270,7 +2338,7 @@ fi
 
 ## We check for the endianess of the machine
 ##
-AP_BYTE_ORDER=`./helpers/TestCompile -r byteorder`
+AP_BYTE_ORDER=`${SHELL} helpers/TestCompile -r byteorder`
 if [ "x$AP_BYTE_ORDER" = "x21" ]; then
     AP_BYTE_ORDER="21" # big endian
 else
@@ -2286,12 +2354,12 @@ echo "#endif" >>$AP_CONFIG_AUTO_H
 ##
 ## Now compare the sizes of off_t to long
 ##
-AP_TYPE_OFF_T=`./helpers/TestCompile -r sizeof off_t`
+AP_TYPE_OFF_T=`${SHELL} helpers/TestCompile -r sizeof off_t`
 if [ "x$AP_TYPE_OFF_T" = "x" ]; then
     AP_TYPE_OFF_T="unknown_off_t"
 fi
 
-AP_TYPE_LONG=`./helpers/TestCompile -r sizeof long`
+AP_TYPE_LONG=`${SHELL} helpers/TestCompile -r sizeof long`
 if [ "x$AP_TYPE_LONG" = "x" ]; then
     AP_TYPE_LONG="unknown_long"
 fi
@@ -2313,7 +2381,7 @@ fi
 ##
 ## Now see of void * is as big as a quad (long long)
 ##
-AP_TYPE_VOID_P=`./helpers/TestCompile -r sizeof 'void *'`
+AP_TYPE_VOID_P=`${SHELL} helpers/TestCompile -r sizeof 'void *'`
 if [ "x$AP_TYPE_VOID_P" = "x" ]; then
     AP_TYPE_VOID_P="unknown_void_p"
 fi
@@ -2387,7 +2455,7 @@ if [ "x$OS" = "xTPF" ] ; then
     :
 else
    echo " + doing sanity check on compiler and options"
-   if ./helpers/TestCompile $vflag sanity; then
+   if ${SHELL} ./helpers/TestCompile $vflag sanity; then
       :
    else
       if [ "x$vflag" = "x-v" ] ; then
@@ -2401,7 +2469,7 @@ else
       echo "** Apache requires an ANSI C Compiler, such as gcc. "
       echo ""
       echo "======== Error Output for sanity check ========"
-      (./helpers/TestCompile -v sanity) 2>&1
+      (${SHELL} ./helpers/TestCompile -v sanity) 2>&1
       echo "============= End of Error Report ============="
       echo ""
       echo " Aborting!"
@@ -2422,15 +2490,15 @@ sed -e "s#@@Configuration@@#$file#" "Makefile.tmpl" >>Makefile
 MAKEDIRS="support $SUBDIRS"
 for dir in $MAKEDIRS ; do
 	echo Creating Makefile in $dir
-	./helpers/mfhead $dir $file > $dir/Makefile
+	${SHELL} helpers/mfhead $dir $file > $dir/Makefile
 	$CAT Makefile.config $dir/Makefile.tmpl |\
-	sed -e "s:^SRCDIR=.*:SRCDIR=`./helpers/fp2rp $dir`:" >> $dir/Makefile
+	sed -e "s:^SRCDIR=.*:SRCDIR=`${SHELL} helpers/fp2rp $dir`:" >> $dir/Makefile
 done
 
 ####################################################################
 ## Now create the lib/Makefile
 ##
-./helpers/mfhead modules $file > lib/Makefile
+${SHELL} helpers/mfhead modules $file > lib/Makefile
 $CAT Makefile.config | sed -e 's:^SRCDIR=.*:SRCDIR=..:' >> lib/Makefile
 
 $CAT << EOF >> lib/Makefile
@@ -2456,15 +2524,15 @@ EOF
 
 for dir in $APLIBDIRS ; do
 	echo Creating Makefile in lib/$dir
-	./helpers/mfhead lib/$dir $file > lib/$dir/Makefile
+	${SHELL} helpers/mfhead lib/$dir $file > lib/$dir/Makefile
 	$CAT Makefile.config lib/$dir/Makefile.tmpl |\
-	sed -e "s:^SRCDIR=.*:SRCDIR=`./helpers/fp2rp lib/$dir`:" >> lib/$dir/Makefile
+	sed -e "s:^SRCDIR=.*:SRCDIR=`${SHELL} helpers/fp2rp lib/$dir`:" >> lib/$dir/Makefile
 done
 
 ####################################################################
 ## Now create the modules/Makefile
 ##
-./helpers/mfhead modules $file > modules/Makefile
+${SHELL} helpers/mfhead modules $file > modules/Makefile
 $CAT Makefile.config | sed -e 's:^SRCDIR=.*:SRCDIR=..:' >> modules/Makefile
 
 $CAT << EOF >> modules/Makefile
@@ -2493,9 +2561,9 @@ EOF
 for moddir in $AUTODIRS ; do
 	echo "Creating Makefile in $moddir"
 
-    ./helpers/mfhead $moddir $file > $moddir/Makefile
+    ${SHELL} helpers/mfhead $moddir $file > $moddir/Makefile
 	$CAT Makefile.config |\
-	sed -e "s:^SRCDIR=.*:SRCDIR=`./helpers/fp2rp $moddir`:" >> $moddir/Makefile
+	sed -e "s:^SRCDIR=.*:SRCDIR=`${SHELL} helpers/fp2rp $moddir`:" >> $moddir/Makefile
 	$CAT << 'EOF' >> $moddir/Makefile
 ##
 ##  Default Makefile options from Configure script
